name: iOS CI - Build, Test, and Upload to SonarCloud and Codecov

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-sonar-codecov:
    name: Build & Test
    runs-on: macos-latest

    env:
      DEVELOPER_DIR: /Applications/Xcode_16.2.app/Contents/Developer
      SONAR_SCANNER_OPTS: "-Dsonar.verbose=true"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Ruby (needed for some CocoaPods setups)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Dependencies
        run: |
          xcodebuild -resolvePackageDependencies

      - name: Run Tests with Coverage
        run: |
          xcodebuild test \
            -scheme RelationshipCoach \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            -enableCodeCoverage YES \
            -resultBundlePath TestResults

      - name: Convert coverage to lcov
        run: |
          gem install slather
          slather coverage --scheme MyApp --workspace RelationshipCoach.xcodeproj --binary-basename MyApp .

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          name: codecov-ios
          fail_ci_if_error: true

      - name: Install SonarCloud Scanner
        run: |
          brew install sonar-scanner

      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.organization=manikanta-nandam \
            -Dsonar.projectKey=nanirocks125_RelationshipCoach \
            -Dsonar.sources=. \
            -Dsonar.language=swift \
            -Dsonar.swift.coverage.reportPaths=coverage/lcov.info \
            -Dsonar.c.file.suffixes=- \
            -Dsonar.cpp.file.suffixes=- \
            -Dsonar.objc.file.suffixes=-

