# .github/workflows/ios-ci.yml
name: iOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
# ──────────────────── Job 1 ────────────────────
  build-and-test:
    runs-on: macos-14     # “macos-latest” already points at Sonoma (14)
    timeout-minutes: 45

    steps:
    # 1️⃣ Checkout --------------------------------------------------------------
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0            # needed for Sonar to link issues to commits

    # 2️⃣ Select Xcode ----------------------------------------------------------
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'     # or any version available on the runner

    # 3️⃣ Tooling (Sonar scanner & wrapper) ------------------------------------
    - name: Install SonarScanner + Build‑Wrapper
      run: |
        brew install sonar-scanner        # installs both binaries
        # Add <brew>/opt/sonar-scanner/libexec/bin to PATH for this job
        echo "$(brew --prefix sonar-scanner)/libexec/bin" >> "$GITHUB_PATH"

    - name: Locate build-wrapper and run xcodebuild
      run: |
        mkdir -p sonar-build-wrapper-output

        # Locate the wrapper inside sonar-scanner's libexec folder
        BW_PATH="$(brew --prefix)/opt/sonar-scanner/libexec/bin/build-wrapper-macosx-x86"

        # Sanity check: fail if not found
        if [ ! -x "$BW_PATH" ]; then
          echo "❌ Build wrapper not found at: $BW_PATH"
          ls -l "$(brew --prefix)/opt/sonar-scanner/libexec/bin"
          exit 1
        fi

        # Now run the wrapper with xcodebuild
        "$BW_PATH" --out-dir sonar-build-wrapper-output \
          xcodebuild test \
            -project RelationshipCoach.xcodeproj \
            -scheme RelationshipCoach \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -derivedDataPath build \
            -enableCodeCoverage YES \
            CODE_SIGNING_ALLOWED=NO

    # 6️⃣ Export coverage to JSON/XML (Codecov & Sonar) -------------------------
    - name: Export coverage
      run: |
        mkdir -p sonar-reports
        xcresult=$(ls build/Logs/Test | grep '\.xcresult$' | head -n1)
        xcrun xccov view --report --json "build/Logs/Test/$xcresult" \
          > sonar-reports/coverage.json

    # 7️⃣ Upload artifacts ------------------------------------------------------
    - uses: actions/upload-artifact@v4
      with:
        name: sonar-build-wrapper-output
        path: sonar-build-wrapper-output
    - uses: actions/upload-artifact@v4
      with:
        name: sonar-coverage
        path: sonar-reports/coverage.json

# ──────────────────── Job 2 ────────────────────
  sonarqube:
    runs-on: macos-14
    needs: build-and-test

    steps:
    - uses: actions/checkout@v4
      with: { fetch-depth: 0 }

    - uses: actions/download-artifact@v4
      with: { name: sonar-build-wrapper-output, path: sonar-build-wrapper-output }
    - uses: actions/download-artifact@v4
      with: { name: sonar-coverage, path: sonar-reports }

    - run: brew install sonar-scanner
    - name: SonarCloud scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
          -Dsonar.projectKey=nanirocks125_RelationshipCoach \
          -Dsonar.organization=manikanta-nandam \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.swift.coverage.reportPath=sonar-reports/coverage.json \
          -Dsonar.cfamily.build-wrapper-output=sonar-build-wrapper-output

# ──────────────────── Job 3 ────────────────────
  codecov:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with: { name: sonar-coverage, path: sonar-reports }
    - uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: sonar-reports/coverage.json
        flags: unittests
