# Name of your workflow
name: iOS CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4

      # # ADD THIS STEP to see what Xcode versions are available
      # - name: List Available Xcode Versions
      #   run: ls /Applications | grep Xcode

      # # UPDATE THIS STEP with the name you find from the step above
      # - name: Select Xcode
      #   run: |
      #     # The name might be Xcode_16_beta.app or something similar.
      #     # Replace 'Xcode_16.2.app' with the name you see in the log.
      #     sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

      # - name: Build and Test
      #   run: |
      #     xcodebuild clean build test \
      #       -project RelationshipCoach.xcodeproj \
      #       -scheme "RelationshipCoach" \
      #       -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' \
      #       -enableCodeCoverage YES
      #       CODE_SIGN_IDENTITY="" \
      #       CODE_SIGNING_REQUIRED=NO

      # - name: Run Xcode Analyzer
      #   run: |
      #     xcodebuild analyze \
      #       -project RelationshipCoach.xcodeproj \
      #       -scheme "RelationshipCoach" \
      #       -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' \

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step to cache the correct (Intel) SonarScanner directory
      - name: Cache SonarScanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: sonar-scanner-5.0.1.3006-macosx-x86_64
          key: sonar-scanner-5.0.1-${{ runner.os }}
      
      # Download and set up the Intel (x86_64) version
      - name: Download and set up SonarScanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          curl -O -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-macosx-x86_64.zip
          unzip sonar-scanner-cli-5.0.1.3006-macosx-x86_64.zip
      
      # Add the Intel (x86_64) version of the scanner to the system PATH
      - name: Add SonarScanner to PATH
        run: echo "$(pwd)/sonar-scanner-5.0.1.3006-macosx-x86_64/bin" >> $GITHUB_PATH

      # Step 3: Run the analysis using the CLI
      - name: Run SonarCloud Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.organization=manikanta-nandam \
            -Dsonar.projectKey=nanirocks125_RelationshipCoach
