# Name of your workflow
name: iOS CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ADD THIS STEP to see what Xcode versions are available
      - name: List Available Xcode Versions
        run: ls /Applications | grep Xcode

      # UPDATE THIS STEP with the name you find from the step above
      - name: Select Xcode
        run: |
          # The name might be Xcode_16_beta.app or something similar.
          # Replace 'Xcode_16.2.app' with the name you see in the log.
          sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

      - name: Build and Test
        run: |
          xcodebuild clean build test \
            -project RelationshipCoach.xcodeproj \
            -scheme "RelationshipCoach" \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO

      - name: Run Xcode Analyzer
        run: |
          xcodebuild analyze \
            -project RelationshipCoach.xcodeproj \
            -scheme "RelationshipCoach" \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' \
