# .github/workflows/ios-ci.yml

name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: macos-15 # use macos-13 or newer

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2' # Use available Xcode version; adjust as needed

      - name: Install SonarScanner
        run: brew install sonar-scanner

      - name: Install CocoaPods (if using Pods)
        run: pod install || echo "No Podfile found, skipping pod install"

      - name: Find SonarQube Build Wrapper
        id: find_bw
        run: |
          bw_path=$(find "$(brew --prefix sonar-scanner)/libexec" -name "build-wrapper-macosx-x86" | head -n 1)
          echo "path=$bw_path" >> $GITHUB_OUTPUT

      - name: Build & Test with Code Coverage + Build Wrapper
        run: |
          mkdir -p sonar-build-wrapper-output
          "${{ steps.find_bw.outputs.path }}" --out-dir sonar-build-wrapper-output \
            xcodebuild test \
              -project RelationshipCoach.xcodeproj \
              -scheme RelationshipCoach \
              -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
              -enableCodeCoverage YES \
              CODE_SIGNING_ALLOWED=NO

      - name: Export Code Coverage Report
        run: |
          mkdir -p sonar-reports
          xcrun xccov view --report --json ./Build/Logs/Test/*.xcresult > sonar-reports/coverage.json
          # Optional: Convert to cobertura.xml if required for SonarCloud/Codecov

      - name: Upload Build Wrapper
        uses: actions/upload-artifact@v4
        with:
          name: sonar-build-wrapper-output
          path: sonar-build-wrapper-output

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: sonar-coverage
          path: sonar-reports/coverage.json

  sonarqube:
    name: SonarCloud Scan
    runs-on: macos-13
    needs: build-and-test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Build Wrapper
        uses: actions/download-artifact@v4
        with:
          name: sonar-build-wrapper-output
          path: sonar-build-wrapper-output

      - name: Download Coverage Report
        uses: actions/download-artifact@v4
        with:
          name: sonar-coverage
          path: sonar-reports

      - name: Install SonarScanner
        run: brew install sonar-scanner

      - name: Run SonarScanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner

  codecov:
    name: Upload to Codecov
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Coverage Report
        uses: actions/download-artifact@v4
        with:
          name: sonar-coverage
          path: sonar-reports

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: sonar-reports/coverage.json
